### PR TITLE
 Add "x64"architecture from WDK. (Non-automatic)

### PR DESCRIPTION
**Pull request by DavidLogic**

### CODE REVIEW

**Comment by MlgmXyysd** [comment]
Is utilities from Git for Windows 64 bit?

**Comment by DavidLogic** [comment]
No, I didn't replace them. I don't think the Git will impact the repack roll, so I only replaced the SDK.

**Comment by DavidLogic** [comment]
Thank you.

**Comment by MlgmXyysd** [comment]
Git Split removed https://github.com/WSA-Community/WSAPackagingTool/commit/ac552918afb3094973a6f9f9611df1ffc7e23e16

**Pull request merged**
